From a TODO in #1221. Add documentation for contributors.
sharkdp/bat pull request #1348
Opened 2020-10-27 03:57 UTC by adrian-rivera

This changes the README file and adds a new section `Contributors`.
This section includes instructions to remind contributors to make an
update to the changelog.

2020-10-27 05:54 UTC, keith-hall requested changes
Thanks for your contribution.
As per the comment at https://github.com/sharkdp/bat/issues/1211#issuecomment-706392560, I think we ideally want this info in a separate `CONTRIBUTING.md` file, which could be linked to from the readme.

2020-10-27 05:54 UTC, keith-hall commented on README.md
> +See the next examples taken from `CHANGELOG.md`
```suggestion
See the following examples taken from `CHANGELOG.md`
```
Note, I'm not sure we really need to call out some real examples from the changelog here, the instructions we post on PRs is (IMO) quite concise and clear:

> Could you please add an entry to the "unreleased" section in CHANGELOG.md? The format for entries is:
> `- Description what has been changed, see #123 (@user)`
> (where `#123` links to the bug ticket and/or the PR and user is your username.)

2020-10-27 05:54 UTC, keith-hall commented on README.md
> +Please don't forget to update `CHANGELOG.md` and describe your changes, this makes the release of a new `bat` version much easier.
```suggestion
Please don't forget to update `CHANGELOG.md` and describe your changes (in the "unreleased" section), as this makes the release of a new `bat` version much easier.
```

2020-10-27 05:54 UTC, keith-hall commented on README.md
> +Each entry should follow the next format:
```suggestion
Each entry should follow the following format:
```

2020-10-29 06:21 UTC, eth-p commented
Although there isn't really any standard for this, I think `CONTRIBUTING.MD` is used more often than `CONTRIBUTORS.MD`.

For example, this is what Hacktoberfest has to say:

> ### Do: Follow a repository's contribution guidelines
> 
> Almost every repo looking for help has a `CONTRIBUTING.md` file in it, read it first!

2020-10-29 06:42 UTC, adrian-rivera commented
> I feel like the file should be renamed. Although there isn't really any standard for this, I think `CONTRIBUTING.MD` is used more often than `CONTRIBUTORS.MD`.
> 
> For example, this is what Hacktoberfest has to say:
> 
> > ### Do: Follow a repository's contribution guidelines
> > Almost every repo looking for help has a `CONTRIBUTING.md` file in it, read it first!

Yep, I think you are right, `CONTRIBUTING` seems to be widely use, I'll do the change

2020-10-29 18:54 UTC, sharkdp approved these changes
Thank you for starting this @adrian-rivera. I added a few more sections to the `CONTRIBUTING.md` file.

@eth-p @keith-hall Let me know if you think we should add anything else to the document.

2020-10-29 18:58 UTC, eth-p approved these changes
Looks good to me!

2020-10-29 19:16 UTC, merged