Warn when building assets from files if some referenced contexts are missing
sharkdp/bat pull request #1771
Opened 2021-08-01 19:44 UTC by keith-hall

Upgrade to syntect 4.6.0 and add a warning to stdout when building assets from files and some context references are unresolved. Fixes #1616 and makes it easier to work on #915 and prevent such cases occurring again in future :)

2021-08-01 20:17 UTC, Enselic commented on src/assets.rs
> +        if missing_contexts.len() > 0 {
Nice! Just fix this lint and this PR is golden:

```
warning: length comparison to zero
   --> src/assets.rs:116:12
    |
116 |         if missing_contexts.len() > 0 {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: using `!is_empty` is clearer and more explicit: `!missing_contexts.is_empty()`
    |
    = note: `#[warn(clippy::len_zero)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
```

I did a test-run of the code and it seemed to work fine for me too :)

2021-08-01 20:18 UTC, Enselic approved these changes

2021-08-01 21:17 UTC, sharkdp approved these changes

2021-08-02 07:49 UTC, Enselic approved these changes

2021-08-02 07:53 UTC, Enselic commented
@keith-hall Oh, I just noticed, seems like you forgot to git add the changes to `Cargo.lock` ?

2021-08-02 07:54 UTC, Enselic requested changes
Cargo.lock seems forgotten?

2021-08-02 11:30 UTC, Enselic commented
Our CI is supposed to detect this, but it appears as if us forgetting to pass `--locked` to early `cargo` commands fixed `Cargo.lock` for later commands.

I just created a [PR](https://github.com/sharkdp/bat/pull/1772) that fixes this. I verified that with this CI fix, this PR would cause [CI to fail](https://github.com/Enselic/bat/pull/19/checks):

2021-08-02 19:49 UTC, Enselic approved these changes
:+1:

2021-08-02 19:55 UTC, merged