Recognize $BAT_CONFIG_DIR and give it precedence over $XDG_CONFIG_HOME
sharkdp/bat pull request #1797
Opened 2021-08-12 22:12 UTC by billrisher

This PR closes issue #1727

I added a nearly-identical test case to one that already exists, for verbosity's sake I left it there but I understand if we'd want to wrap the new test case into an existing one.

2021-08-13 02:29 UTC, billrisher commented on src/bin/bat/directories.rs
> +///  The fallback directories are `~/.cache/bat` and `~/.config/bat`, respectively.
There's probably a better way to word this if anyone has any ideas.

2021-08-14 16:59 UTC, keith-hall approved these changes

2021-08-14 17:05 UTC, sharkdp commented on tests/integration_tests.rs
> +#[test]
Can you please add the new env. variable to `bat_raw_command_with_config` to make sure it is *removed from the environment* for all integration tests? This is important in order to make sure that tests pass, even in environments where a user has set some env. variables.

2021-08-14 17:08 UTC, sharkdp commented on tests/integration_tests.rs
> +        );
Another idea for a (maybe simpler) test would be similar to `config_read_arguments_from_file`. Wouldn't require a temp. directory. But I guess this is fine as well. Thank you for writing a test!

2021-08-14 17:10 UTC, sharkdp commented on CHANGELOG.md
> +- $BAT_CONFIG_DIR is now a recognized environment variable and has precedent over $XDG_CONFIG_HOME. (@billrisher)
```suggestion
- `$BAT_CONFIG_DIR` is now a recognized environment variable. It has precedence over `$XDG_CONFIG_HOME`, see #1727 (@billrisher)
```

2021-08-14 17:11 UTC, sharkdp commented
Thank you very much for your contribution!

2021-08-14 17:11 UTC, sharkdp requested changes
Thank you very much for your contribution!

2021-08-14 19:51 UTC, sharkdp approved these changes

2021-08-14 20:02 UTC, merged