fix Bash completion on macOS
sharkdp/bat pull request #2074
Opened 2022-02-13 11:25 UTC by joshpencheon

Issue #2066 reports that bash completion is broken on macOS. This is because the version of `bash-completion` that's often packed on macOS via Home-brew is v1.3, which doesn't include the missing `_init_completion` function.

This PR adopts a pattern seen across many other projects (e.g. `tmux`/ `gh` / `kubectl` /  `helm`, some of which use the Cobra Go library to [autogenerate their completion](https://github.com/spf13/cobra/blob/master/bash_completionsV2.go#L32-L38)) to add a shim function with the minimal required functionality.

Completion now works for me on both macOS 10.15.7 and Ubuntu 22.04.

2022-02-13 12:30 UTC, sharkdp commented
Thank you very much for your contribution!

@scop Would you mind having a short look at this?

2022-02-13 17:17 UTC, scop requested changes
Looks quite concise and ok to me, if support for such old versions is desired. Not tested as I don't have easy access to them. (An alternative would be to be more accurate that we require bash-completion >= 2, but that implies bash >= 4 and causes some extra complications for macOS users as noted in my comment about the changelog entry.)

I haven't examined the shim in depth, but based on the references it appears to be quite battle tested.

2022-02-13 17:17 UTC, scop commented on assets/completions/bat.bash.in
> +	_split_longopt && split=true
This should go in the above `__bat_init_completion` block or be done within its body, it's unnecessary with bash-completion 2+ and its `_init_completion`.

2022-02-13 17:17 UTC, scop commented on CHANGELOG.md
> +- Fix bash completion on macOS. See #2066 (@joshpencheon)
```suggestion
- Fix bash completion on bash 3.x and bash-completion 1.x. See #2066 (@joshpencheon)
```

"on macOS" is inaccurate, there's nothing macOS specific here. The unmodified completion code would work on macOS too if one installs a recent enough bash and bash-completion@2 from homebrew.

2022-02-13 19:12 UTC, sharkdp commented
Thanks! Both of you!

2022-02-13 19:12 UTC, sharkdp approved these changes

2022-02-14 15:37 UTC, joshpencheon commented
@sharkdp are you happy for me to merge this PR, or do you follow a different process? Thanks!

2022-02-24 06:56 UTC, Enselic commented
I am personally not well-versed in bash completion to make a judgement call, but I fully trust the rest of you.

Merging so that this will be included in the upcoming 0.19.1 release.

2022-02-24 06:57 UTC, merged