Add `.mts` and `.cts` to TypeScript file extensions
sharkdp/bat pull request #2236
Opened 2022-07-04 14:02 UTC by kidonng

These are [TypeScript counterparts](https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
) of Node.js `.mjs` and `.cjs` file extensions.

See also:

- https://github.com/github/linguist/pull/5905
- https://github.com/starship/starship/pull/3734

2022-08-12 14:42 UTC, Enselic requested changes
Thank you for the contribution! Do you think we can upstream this change?

The file you changed is converted from a .tmLanguage, which makes maintenance a bit of a headache. I think we need to at least add some basic regression tests if we are to patch this file ourselves. Not sure what other maintainers think.

See https://github.com/sharkdp/bat/blob/master/doc/assets.md for some general pointers on adding tests.

2022-09-02 21:47 UTC, sharkdp commented
@kidonng Any update on this?

2022-09-04 20:07 UTC, sharkdp commented
The upstream repository seems to be unmaintained (https://github.com/microsoft/TypeScript-Sublime-Plugin/issues/786). So let's just patch this file and put a simply regression test in place.

2022-09-04 20:08 UTC, sharkdp approved these changes

2022-09-04 20:13 UTC, Enselic approved these changes

2022-09-04 20:20 UTC, merged