Bump MSRV to 1.70.0
sharkdp/bat pull request #2651
Opened 2023-08-28 14:33 UTC by mataha

The intention is to take advantage of `std::io::IsTerminal` that landed in 1.70.0, both in `bat` and its dependencies (`clap`, `grep-cli`).

This will fix #2570 as well - `grep-cli` 0.1.9 has a patch for that.

2023-08-28 15:49 UTC, Enselic requested changes
I am strongly in favor of this change. But can you please undo your changes that made some multi line dependency declarations single line?

2023-08-29 14:07 UTC, Enselic commented
Thanks! Looks good to me. Also please add an entry about the MSRV bump in CHANGELOG.md.

Once that is done I think we should merge this. A change like this tends to conflict with other changes over time. @sharkdp has previously said that it is fine to bump MSRV as soon as we have the slightest reason to bump it.

2023-08-31 18:37 UTC, mataha commented
> Thanks! Looks good to me. Also please add an entry about the MSRV bump in CHANGELOG.md.

Done.

2023-09-01 03:42 UTC, Enselic approved these changes

2023-09-01 03:42 UTC, merged